CREATE DATABASE supply_chain;
use supply_chain;
select * from supply_chain_data;

-- we divided the dataset into multiple relational tables--

CREATE TABLE Products (
    product_id INT AUTO_INCREMENT PRIMARY KEY,
    sku VARCHAR(50) NOT NULL UNIQUE,
    product_type VARCHAR(50),
    price DECIMAL(10,2)
);
INSERT INTO Products (sku, product_type, price)
SELECT DISTINCT SKU,
`Product_type`,
Price
FROM supply_chain_data;

select * from Products;

CREATE TABLE Sales ( 
sale_id INT PRIMARY KEY AUTO_INCREMENT, 
product_id INT, 
number_of_products_sold INT, 
revenue_generated DECIMAL(12,2), 
customer_demographics VARCHAR(50), 
FOREIGN KEY (product_id) REFERENCES Products(product_id) );

INSERT INTO Sales (product_id, number_of_products_sold, revenue_generated, customer_demographics)
SELECT p.product_id,r.`Number_products_sold`,r.`Revenue_generated`,
r.`Customer_demographics`
FROM supply_chain_data r
JOIN Products p 
ON r.SKU = p.sku;

select * from Sales;

CREATE TABLE Inventory (
    inventory_id INT PRIMARY KEY AUTO_INCREMENT,
    product_id INT,
    availability INT,
    stock_levels INT,
    order_quantities INT,
    FOREIGN KEY (product_id) REFERENCES Products(product_id)
);

INSERT INTO Inventory (product_id, availability, stock_levels, order_quantities)
SELECT p.product_id,r.`Availability`,r.`Stock_levels`,
r.`Order_quantities`
FROM supply_chain_data r
JOIN Products p 
ON r.sku = p.sku;

select * from Inventory;

CREATE TABLE Suppliers (
    supplier_id INT PRIMARY KEY AUTO_INCREMENT,
    supplier_name VARCHAR(100),
    location VARCHAR(100),
    production_volumes INT,
    manufacturing_lead_time INT,
    manufacturing_costs DECIMAL(12,2),
    inspection_results VARCHAR(50),
    defect_rates DECIMAL(5,2)
);

INSERT INTO Suppliers (supplier_name, location, production_volumes, manufacturing_lead_time, manufacturing_costs, inspection_results, defect_rates)
SELECT DISTINCT r.Supplier_name, r.Location,
r.`Production_volumes`,r.`Manufacturing_lead_time`,
r.`Manufacturing_costs`,r.`Inspection_results`,
r.`Defect_rates`
FROM supply_chain_data r;

select * from Suppliers;

CREATE TABLE Logistics (
    logistics_id INT PRIMARY KEY AUTO_INCREMENT,
    product_id INT,
    supplier_id INT,
    lead_time INT,
    shipping_times INT,
    shipping_carriers VARCHAR(100),
    transportation_modes VARCHAR(50),
    routes VARCHAR(50),
    shipping_costs DECIMAL(12,2),
    total_costs DECIMAL(12,2),
    FOREIGN KEY (product_id) REFERENCES Products(product_id),
    FOREIGN KEY (supplier_id) REFERENCES Suppliers(supplier_id)
);

INSERT INTO Logistics (
    product_id, supplier_id, lead_time, shipping_times, shipping_carriers, 
    transportation_modes, routes, shipping_costs, total_costs
)
SELECT p.product_id,s.supplier_id,r.Lead_time,            
r.Shipping_times,r.Shipping_carriers,
r.Transportation_modes,r.Routes,
r.Shipping_costs,
r.Costs                  
FROM supply_chain_data r
JOIN Products p 
ON r.SKU = p.sku
JOIN Suppliers s 
ON r.Supplier_name = s.Supplier_name
AND r.Location = s.Location;

select * from Logistics;

-- All table -- 
select * from Products;
select * from Sales;
select * from Inventory;
select * from Suppliers;
select * from Logistics;

-- 1. What is the total revenue generated by each product type, and which type has the highest average revenue per sale? -- 

SELECT p.product_type AS category,SUM(s.revenue_generated) AS total_revenue,
AVG(s.revenue_generated) AS avg_revenue_per_sale
FROM Sales s
JOIN Products p ON s.product_id = p.product_id
GROUP BY p.product_type
ORDER BY total_revenue DESC;

-- 2. Which products have the highest revenue per unit sold? -- 

SELECT p.product_type AS category,p.sku,p.price AS unit_price,
SUM(s.number_of_products_sold) AS total_units_sold,
SUM(s.revenue_generated) AS total_revenue,
ROUND(SUM(s.revenue_generated) / SUM(s.number_of_products_sold), 2) AS revenue_per_unit
FROM Sales s
JOIN Products p 
ON s.product_id = p.product_id
GROUP BY p.product_type, p.sku, p.price
ORDER BY revenue_per_unit DESC
LIMIT 10;

-- 3.What is the sales distribution by customer demographics, and identify any demographic biases?

SELECT s.customer_demographics AS demographic, SUM(s.revenue_generated) AS total_revenue,
ROUND( (SUM(s.revenue_generated) / (SELECT SUM(revenue_generated) FROM Sales)) * 100, 2 ) AS revenue_pct
FROM Sales s
GROUP BY s.customer_demographics
ORDER BY total_revenue DESC;

-- 4. Rank products by total units sold descending, and flag those with sales below average.

WITH product_sales AS (
    SELECT 
	p.product_id,p.sku,p.product_type,
	SUM(s.number_of_products_sold) AS total_units_sold
    FROM Sales s
    JOIN Products p 
	ON s.product_id = p.product_id
    GROUP BY p.product_id, p.sku, p.product_type
),
avg_calc AS (
    SELECT AVG(total_units_sold) AS avg_units_sold
    FROM product_sales
)
SELECT ps.product_type,ps.sku,ps.total_units_sold,
RANK() OVER (ORDER BY ps.total_units_sold DESC) AS sales_rank,
    CASE 
        WHEN ps.total_units_sold < (SELECT avg_units_sold FROM avg_calc) 
        THEN 'Below Average'
        ELSE 'Above Average'
    END AS performance_flag
FROM product_sales ps
ORDER BY sales_rank;

-- What is the overall sales conversion rate if we assume availability as potential sales opportunities?

SELECT p.product_type,ROUND(SUM(s.number_of_products_sold) * 1.0 / SUM(i.availability), 4) AS conversion_rate
FROM Sales s
JOIN Inventory i 
ON s.product_id = i.product_id
JOIN Products p 
ON s.product_id = p.product_id
GROUP BY p.product_type
ORDER BY conversion_rate DESC;


-- What is the inventory turnover ratio for each product , and which products are turning over slowest?

SELECT p.product_type,p.sku,SUM(s.number_of_products_sold) AS total_units_sold,
ROUND(AVG(i.stock_levels), 2) AS avg_stock,
CASE 
WHEN ROUND(AVG(i.stock_levels), 2) = 0 AND SUM(s.number_of_products_sold) > 0 
THEN NULL   -- avoid divide by zero
ELSE ROUND(SUM(s.number_of_products_sold) * 1.0 / NULLIF(AVG(i.stock_levels), 0), 2)
END AS inventory_turnover,
CASE 
WHEN ROUND(AVG(i.stock_levels), 2) = 0 AND SUM(s.number_of_products_sold) > 0 
            THEN '⚠️ Data Issue (stock=0 but sales exist)'
WHEN (SUM(s.number_of_products_sold) * 1.0 / NULLIF(AVG(i.stock_levels), 0)) < 1 
            THEN '⚠️ Slow Moving'
        ELSE 'Healthy'
END AS turnover_flag
FROM Sales s
JOIN Inventory i 
ON s.product_id = i.product_id
JOIN Products p 
ON s.product_id = p.product_id
GROUP BY p.product_type, p.sku
ORDER BY inventory_turnover ASC;

-- Identify products at risk of stockout: those where stock_levels < 10% of order_quantities

SELECT p.product_type,p.sku,i.stock_levels,i.order_quantities,
ROUND((i.stock_levels * 1.0 / NULLIF(i.order_quantities, 0)) * 100, 2) AS stock_to_order_pct,
CASE 
WHEN i.order_quantities = 0 THEN '⚠️ Data Issue (order qty = 0)'
WHEN (i.stock_levels * 1.0 / i.order_quantities) < 0.10 THEN '🚨 At Risk of Stockout'
ELSE 'OK'
END AS stockout_flag
FROM Inventory i
JOIN Products p 
ON i.product_id = p.product_id
ORDER BY stock_to_order_pct ASC;

-- What is the average availability percentage across product types, and how does it impact sales volume?

WITH availability_stats AS (
SELECT p.product_type,ROUND(AVG(i.availability * 1.0 / NULLIF(i.availability + i.stock_levels, 0)) * 100, 2) AS avg_availability_pct
FROM Inventory i JOIN Products p ON i.product_id = p.product_id
GROUP BY p.product_type
),
sales_stats AS (
SELECT 
p.product_type,
SUM(s.number_of_products_sold) AS total_units_sold
FROM Sales s
JOIN Products p 
ON s.product_id = p.product_id
GROUP BY p.product_type
)
SELECT a.product_type,a.avg_availability_pct,s.total_units_sold,
ROUND(s.total_units_sold / NULLIF(a.avg_availability_pct, 0), 2) AS units_per_avail_pct
FROM availability_stats a
JOIN sales_stats s 
ON a.product_type = s.product_type
ORDER BY a.avg_availability_pct DESC;

-- What is the average defect rate by supplier_name, and rank suppliers from best to worst?

SELECT supplier_name,ROUND(AVG(defect_rates), 2) AS avg_defect_rate,
ROW_NUMBER() OVER (ORDER BY AVG(defect_rates) ASC) AS quality_rank
FROM Suppliers
GROUP BY supplier_name
ORDER BY avg_defect_rate ASC;

-- Calculate the total manufacturing cost per unit produced for each supplier, and identify cost outliers.

WITH supplier_costs AS (
    SELECT 
        supplier_name,
        SUM(manufacturing_costs) AS total_manufacturing_costs,
        SUM(production_volumes) AS total_production_volumes,
        (SUM(manufacturing_costs) / NULLIF(SUM(production_volumes),0)) AS cost_per_unit
    FROM Suppliers
    GROUP BY supplier_name
)

SELECT 
    supplier_name,
    total_manufacturing_costs,
    total_production_volumes,
    ROUND(cost_per_unit, 2) AS cost_per_unit,
    CASE 
        WHEN cost_per_unit > (SELECT AVG(cost_per_unit) FROM supplier_costs) 
        THEN '⚠️ Above Avg (Costly Supplier)'
        ELSE '✅ Efficient Supplier'
    END AS cost_flag
FROM supplier_costs
ORDER BY cost_per_unit DESC;

-- What percentage of suppliers have failed inspections, and what is their impact on defect rates?

SELECT COUNT(CASE WHEN inspection_results = 'Fail' THEN 1 END) * 100.0 / COUNT(*) AS pct_failed_suppliers,
AVG(CASE WHEN inspection_results = 'Fail' THEN defect_rates END) AS avg_defect_rate_failed,
AVG(CASE WHEN inspection_results <> 'Fail' THEN defect_rates END) 
AS avg_defect_rate_passed
FROM Suppliers;

-- Rank suppliers by a score, to recommend top performers.

WITH supplier_scores AS (
    SELECT 
        supplier_id,
        supplier_name,
        defect_rates,
        production_volumes,
        manufacturing_lead_time,
        -- Custom composite score:
        ( (production_volumes / NULLIF(manufacturing_lead_time,0)) * (1 / NULLIF(defect_rates,0)) ) 
            AS performance_score
    FROM Suppliers
)
SELECT 
    supplier_name,
    ROUND(defect_rates,2) AS defect_rate,
    production_volumes,
    manufacturing_lead_time,
    ROUND(performance_score,2) AS performance_score,
    ROW_NUMBER() OVER (ORDER BY performance_score DESC) AS rank_position
FROM supplier_scores
ORDER BY performance_score DESC;

-- What is the average lead_time and shipping_times by transportation_modes, and identify routes with the highest total_costs?

SELECT l.transportation_modes,l.routes,
ROUND(AVG(l.lead_time), 2) AS avg_lead_time,ROUND(AVG(l.shipping_times), 2) AS avg_shipping_time,
SUM(l.total_costs) AS total_route_costs
FROM Logistics l
GROUP BY l.transportation_modes, l.routes
ORDER BY total_route_costs DESC;

-- Calculate the shipping cost per unit for each product_id , and compare across shipping_carriers.

WITH inv_summary AS (
  SELECT product_id, SUM(order_quantities) AS total_units
  FROM Inventory
  GROUP BY product_id
),
log_summary AS (
  SELECT product_id, shipping_carriers, SUM(shipping_costs) AS total_shipping_costs
  FROM Logistics
  GROUP BY product_id, shipping_carriers
)
SELECT 
    p.product_type,
    p.sku,
    l.shipping_carriers,
    l.total_shipping_costs,
    i.total_units,
    ROUND(l.total_shipping_costs / NULLIF(i.total_units,0), 2) AS shipping_cost_per_unit
FROM Products p
JOIN inv_summary i ON p.product_id = i.product_id
JOIN log_summary l ON p.product_id = l.product_id
ORDER BY shipping_cost_per_unit DESC;


-- What is the on-time delivery potential: flag logistics records where lead_time + shipping_times > 30 days as high-risk.

SELECT 
    l.logistics_id,
    l.supplier_id,
    l.product_id,
    l.routes,
    l.lead_time,
    l.shipping_times,
    (l.lead_time + l.shipping_times) AS total_delivery_days,
    CASE 
        WHEN (l.lead_time + l.shipping_times) > 30 THEN '⚠️ High Risk'
        ELSE '✅ On-Time Potential'
    END AS delivery_risk_flag
FROM Logistics l
ORDER BY total_delivery_days DESC;

-- Rank routes by efficiency score, and suggest alternatives for high-cost carriers.
WITH RouteEfficiency AS (
    SELECT
        l.routes,
        l.shipping_carriers,
        l.transportation_modes,
        AVG(l.shipping_costs) AS avg_shipping_cost,
        AVG(l.shipping_times) AS avg_shipping_time,
        -- Efficiency score = lower cost per day → more efficient
        (AVG(l.shipping_costs) / NULLIF(AVG(l.shipping_times), 0)) AS efficiency_score
    FROM Logistics l
    GROUP BY l.routes, l.shipping_carriers, l.transportation_modes
)
SELECT
    routes,
    shipping_carriers,
    transportation_modes,
    avg_shipping_cost,
    avg_shipping_time,
    ROUND(efficiency_score, 2) AS efficiency_score,
    RANK() OVER (ORDER BY efficiency_score ASC) AS efficiency_rank,
    CASE
        WHEN efficiency_score > (
            SELECT AVG(efficiency_score) FROM RouteEfficiency
        ) THEN '⚠️ Consider Alternative'
        ELSE '✅ Efficient'
    END AS recommendation
FROM RouteEfficiency
ORDER BY efficiency_rank;

-- What is the total supply chain cost vs. revenue_generated for each product_id, and calculate profit margin? 

WITH sales_summary AS (
  SELECT product_id, SUM(revenue_generated) AS total_revenue
  FROM Sales
  GROUP BY product_id
),
supplier_costs AS (
  SELECT l.product_id, SUM(sup.manufacturing_costs) AS total_manufacturing_costs
  FROM Logistics l
  JOIN Suppliers sup ON l.supplier_id = sup.supplier_id
  GROUP BY l.product_id
),
logistics_costs AS (
  SELECT product_id, SUM(total_costs) AS total_logistics_costs
  FROM Logistics
  GROUP BY product_id
)
SELECT 
  p.product_id, p.sku, p.product_type,
  ss.total_revenue,
  sc.total_manufacturing_costs,
  lc.total_logistics_costs,
  (sc.total_manufacturing_costs + lc.total_logistics_costs) AS total_supply_chain_cost,
  (ss.total_revenue - (sc.total_manufacturing_costs + lc.total_logistics_costs)) AS profit,
  ROUND(((ss.total_revenue - (sc.total_manufacturing_costs + lc.total_logistics_costs)) / NULLIF(ss.total_revenue,0)) * 100, 2) AS profit_margin_pct
FROM Products p
JOIN sales_summary ss ON p.product_id = ss.product_id
JOIN supplier_costs sc ON p.product_id = sc.product_id
JOIN logistics_costs lc ON p.product_id = lc.product_id
ORDER BY profit_margin_pct DESC;


-- What is the supplier dependency risk: Percentage of production_volumes from suppliers in the same location

WITH location_summary AS (
    SELECT 
        location,
        SUM(production_volumes) AS total_volume
    FROM Suppliers
    GROUP BY location
),
total_all AS (
    SELECT SUM(total_volume) AS grand_total FROM location_summary
)
SELECT 
    ls.location,
    ls.total_volume,
    ROUND(ls.total_volume / ta.grand_total * 100, 2) AS pct_of_total,
    CASE 
        WHEN ls.total_volume / ta.grand_total * 100 > 50 THEN '⚠️ High Dependency'
        WHEN ls.total_volume / ta.grand_total * 100 BETWEEN 25 AND 50 THEN 'Moderate'
        ELSE 'Low Risk'
    END AS risk_level,
    RANK() OVER (ORDER BY ls.total_volume DESC) AS rank_by_volume
FROM location_summary ls
CROSS JOIN total_all ta
ORDER BY pct_of_total DESC;

-- Revenue by demographics linked to product_type and supplier quality

WITH sales_summary AS (
  SELECT s.product_id, s.customer_demographics, SUM(s.revenue_generated) AS total_revenue
  FROM Sales s
  GROUP BY s.product_id, s.customer_demographics
)
SELECT ss.customer_demographics, p.product_type, sup.supplier_name,
ROUND(AVG(sup.defect_rates), 2) AS avg_defect_rate,SUM(ss.total_revenue) AS total_revenue
FROM sales_summary ss
JOIN Products p ON ss.product_id = p.product_id
JOIN Logistics l ON p.product_id = l.product_id
JOIN Suppliers sup ON l.supplier_id = sup.supplier_id
GROUP BY ss.customer_demographics, p.product_type, sup.supplier_name
ORDER BY total_revenue DESC;
